//
//  TesteventViewController.m
//  Owlers
//
//  Created by Biprajit Biswas on 15/10/15.
//  Copyright (c) 2015 JNT. All rights reserved.
//

#import "TesteventViewController.h"
#import "OwlersViewController.h"
#import "SharedPreferences.h"
#import "PGTransactionViewController.h"
#import "PGOrder.h"
@interface TesteventViewController () <PGTransactionDelegate>
{
    int _maleCount, _femaleCount, _coupleCount;
}
@property (weak, nonatomic) IBOutlet UILabel *screenTitle;
@property (weak, nonatomic) IBOutlet UILabel *maleCountLbl;
@property (weak, nonatomic) IBOutlet UILabel *femaleCountLbl;
@property (weak, nonatomic) IBOutlet UILabel *payableMaleCountLbl;
@property (weak, nonatomic) IBOutlet UILabel *payableFemaleCountLbl;
@property (weak, nonatomic) IBOutlet UILabel *payableCoupleCountLbl;
@property (weak, nonatomic) IBOutlet UILabel *malePriceLbl;
@property (weak, nonatomic) IBOutlet UILabel *femalePriceLbl;
@property (weak, nonatomic) IBOutlet UILabel *couplePriceLbl;
@property (weak, nonatomic) IBOutlet UILabel *calculatedMalePriceLbl;
@property (weak, nonatomic) IBOutlet UILabel *calculatedFemalePriceLbl;
@property (weak, nonatomic) IBOutlet UILabel *calculatedCouplePriceLbl;
@property (weak, nonatomic) IBOutlet UILabel *totalPriceLbl;
@property (weak, nonatomic) IBOutlet UILabel *withoutPaymentPriceLbl;
@property (weak, nonatomic) IBOutlet UILabel *payNowPriceLbl;
@property (weak, nonatomic) IBOutlet UIButton *payNowBtn;

@end

@implementation TesteventViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.maleCountLbl.layer.borderWidth = 1.0f;
    self.femaleCountLbl.layer.borderWidth = 1.0f;
    self.maleCountLbl.layer.borderColor = [UIColor colorWithRed:251.0f/255 green:156.0f/255 blue:21.0f/255 alpha:1].CGColor;
    self.femaleCountLbl.layer.borderColor = [UIColor colorWithRed:251.0f/255 green:156.0f/255 blue:21.0f/255 alpha:1].CGColor;
    
    _maleCount = 0;
    _femaleCount = 0;
    _coupleCount = 0;
    
    self.screenTitle.text = self.event.name;
    self.malePriceLbl.text = [NSString stringWithFormat:@"%d",self.event.malePrice];
    self.femalePriceLbl.text = [NSString stringWithFormat:@"%d",self.event.femalePrice];
    self.couplePriceLbl.text = [NSString stringWithFormat:@"%d",self.event.couplePrice];
    [self.payNowBtn setTitle:[NSString stringWithFormat:@"PAY  NOW ( %@ )",self.event.discountTitle] forState:UIControlStateNormal];
    
    [self update];
}

- (IBAction)backBtnAction:(id)sender {
    [self.navigationController popViewControllerAnimated:YES];
}

- (IBAction)maleMinusAction:(id)sender {
    if (_maleCount >= 1) {
        _maleCount--;
        [self update];
    }
}

- (IBAction)malePlusAction:(id)sender {
    _maleCount++;
    [self update];
}

- (IBAction)femaleMinusAction:(id)sender {
    if (_femaleCount >= 1) {
        _femaleCount--;
        [self update];
    }
}

- (IBAction)femalePlusAction:(id)sender {
    _femaleCount++;
    [self update];
}

- (IBAction)continueWithoutPayAction:(id)sender {

}

- (IBAction)payNowAction:(id)sender {

    NSInteger totalPrice = ((_maleCount - _coupleCount)*self.event.malePrice )+ ((_femaleCount - _coupleCount)*self.event.femalePrice) + (_coupleCount*self.event.couplePrice);

    NSInteger discountedPrice  = totalPrice - ((totalPrice * self.event.discountValue)/100);
    NSString *sDiscountedPrice = [NSString stringWithFormat:@"%ld", (long)discountedPrice];


    PGOrder *order = [PGOrder orderForOrderID:[self getUniqueOrderID]//Required:Unique orderID generated by the app
                                   customerID:[[SharedPreferences sharedInstance] getUserID] //Required:Customer ID
                      amount:sDiscountedPrice //Required:Transaction Amount
                customerMail:[[SharedPreferences sharedInstance] getUserEmail]//Optional:Email Id if available
              customerMobile:@"" //Optional:Mobile number if available.
     ];
    
    PGTransactionViewController *txnController = [[PGTransactionViewController alloc] initTransactionForOrder:order];
    txnController.serverType = eServerTypeProduction;
    txnController.delegate = self;
    [self.navigationController pushViewController:txnController animated:YES];
}

- (NSString *)getUniqueOrderID{
    
    
    int fromNumber = arc4random() + 1000000;
    int toNumber   = arc4random() + 10000000;
    int randomNumber = (arc4random()%(toNumber-fromNumber))+fromNumber;
    if (randomNumber < 0) {
        randomNumber = (randomNumber * -1);
    }
    return [NSString stringWithFormat:@"%ld", (long)randomNumber];
}


- (void)update {
    
    self.maleCountLbl.text = [NSString stringWithFormat:@"%d",_maleCount];
    self.femaleCountLbl.text = [NSString stringWithFormat:@"%d",_femaleCount];
    
    if (_maleCount <= _femaleCount) {
        _coupleCount = _maleCount;
    }else {
        _coupleCount = _femaleCount;
    }
    
    self.payableMaleCountLbl.text = [NSString stringWithFormat:@"%d",(_maleCount - _coupleCount)];
    self.payableFemaleCountLbl.text = [NSString stringWithFormat:@"%d",(_femaleCount - _coupleCount)];
    self.payableCoupleCountLbl.text = [NSString stringWithFormat:@"%d",_coupleCount];
    
    if (self.event) {
        self.calculatedMalePriceLbl.text = [NSString stringWithFormat:@"%d",(_maleCount - _coupleCount)*self.event.malePrice];
        self.calculatedFemalePriceLbl.text = [NSString stringWithFormat:@"%d",(_femaleCount - _coupleCount)*self.event.femalePrice];
        self.calculatedCouplePriceLbl.text = [NSString stringWithFormat:@"%d", _coupleCount*self.event.couplePrice];
        
        NSInteger totalPrice = ((_maleCount - _coupleCount)*self.event.malePrice )+ ((_femaleCount - _coupleCount)*self.event.femalePrice) + (_coupleCount*self.event.couplePrice);
        self.totalPriceLbl.text = [NSString stringWithFormat:@"%ld", (long)totalPrice];

        self.withoutPaymentPriceLbl.text = [NSString stringWithFormat:@"%ld", (long)totalPrice];
        NSInteger discountedPrice  = totalPrice - ((totalPrice * self.event.discountValue)/100);
        self.payNowPriceLbl.text = [NSString stringWithFormat:@"%ld", (long)discountedPrice];
    }
}

- (void)didSucceedTransaction:(PGTransactionViewController *)controller response:(NSDictionary *)response{

}

//Called when transaction fails with any reason. Response dictionary will be having details about the failed transaction.
- (void)didFailTransaction:(PGTransactionViewController *)controller error:(NSError *)error response:(NSDictionary *)response{

}

//Called when a transaction is cancelled by the user. Response dictionary will be having details about the cancelled transaction.
- (void)didCancelTransaction:(PGTransactionViewController *)controller error:(NSError*)error response:(NSDictionary *)response{

}

//Called when Checksum HASH generation completes either by PG Server or Merchant Server.
- (void)didFinishCASTransaction:(PGTransactionViewController *)controller response:(NSDictionary *)response{

}


@end
